### ISSUE TITLE
 Error response from daemon: create %cd%: "%cd%" includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by AmmarkoV** [BrainSlugs83/DockerOvrSdk#3]
The command 
```
docker run -it --rm -v %cd%:/proj brainslugs83/ovrsdk /opt/build.sh
```
in https://raw.githubusercontent.com/BrainSlugs83/DockerOvrSdk/master/README.md

should be 
```
docker run -it --rm -v $(pwd):/proj brainslugs83/ovrsdk /opt/build.sh
```
for Linux

**Comment by BrainSlugs83** [comment]
Thanks for letting me know this -- I'm on Windows, so I'm not able to test, but I can update the readme.md to include those instructions.

Edit: ... do you know if it's the same on Mac?
